version: "2"
linters:
  default: standard
  enable:
    # linters
    - asasalint
    - asciicheck
    - bidichk
    - exhaustive
    - nolintlint
    # style
    - misspell
    - dupl
    - dupword
    - funlen
    - goconst
    # - godot
    - godox
    - nestif
    # - revive
    - wsl
    - whitespace
    # complexity
    - exptostd
    # - errcheck
    # - funlen
    - gocyclo
    - lll
    - unconvert
    - wastedassign
    # security
    - gosec
  settings:
    revive:
      enable-all-rules: true
