kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-host
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/host-pv