kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-static
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: 192.168.1.100
    path: /mnt/nfs