kind: Service
type: NodePort
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx
    tier: frontend
spec:
  selector:
    app: nginx
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
# status:
#   clusterIP: 10.96.123.45 # 运行时自动生成
#   endpoints:
#     - ip: 172.17.0.2 # 运行时自动生成
#       port: 80 # 运行时自动生成
#     - ip: 172.17.0.3 # 运行时自动生成
#       port: 80 # 运行时自动生成